---
title: "Pitcher Trackman Averages"
author: "Jack Byrne"
#date: "9/21/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
# p = "Gerard, Chris"
```

```{r games}
library(dplyr)
library(tinytex)
library(ggplot2)
library(data.table)
setwd("C:/Users/Jack/Desktop/School Stuff/VT Baseball/BP Reports/Trackman/Scrimmages-2020")
myfiles <- list.files(pattern="*.csv")
data = rbindlist(lapply(myfiles, fread, header = F, fill = T), fill = T)
names(data) <- as.matrix(data[1, ])
data <- data[-1, ]
data[] <- lapply(data, function(x) type.convert(as.character(x)))
games = subset(data, select = -c(76))
```

```{r scrimmages}
setwd("C:/Users/Jack/Desktop/School Stuff/VT Baseball/BP Reports/Trackman/Scrimmages-2020")
myfiles <- list.files(pattern="*.csv")
dat = rbindlist(lapply(myfiles, fread, header = F, fill = T), fill = T)
names(dat) <- as.matrix(dat[1, ])
dat <- dat[-1, ]
dat[] <- lapply(dat, function(x) type.convert(as.character(x)))
scrimmages = subset(dat, select = -c(76))
```

```{r combine}
library(dplyr)
library(tidyverse)
library(lubridate)
combined <- rbind(scrimmages, games)
combined$RelSpeed <- as.numeric(as.character(combined$RelSpeed))
combined$SpinRate <- as.numeric(as.character(combined$SpinRate))
combined$Tilt <- as.POSIXct(combined$Tilt, format="%H:%M")
combined$RelSpeed <- round(combined$RelSpeed, 0)
combined$SpinRate <- round(combined$SpinRate, -2)
```

```{r table}
library(ggplot2)
library(knitr)
player <- filter(combined, Pitcher == p)
player <- mutate(player, counter = 1)
pitches <- unique(player$TaggedPitchType)
tab <- player %>%
  group_by(TaggedPitchType) %>%
  summarise(Tilt = mean(Tilt, na.rm = T), Spin = round(mean(SpinRate, na.rm = T), 0), 
            Velo = round(mean(RelSpeed, na.rm = T), 0), N = sum(counter, na.rm = T))
tab$Tilt <- format(tab$Tilt, "%H:%M")
tab <- tab %>%
  arrange(desc(N))
kable(tab)


# for (j in pitches) {
#   pitch <- filter(player, TaggedPitchType == j)
#   print(ggplot(pitch, aes(x=RelSpeed))+geom_histogram()+labs(title =paste(p, j, ": Velo"),
#         x = "Velocity (mph)", y = "Frequency",
#         caption = "Trackman Data"))
# }
# ggplot(player, aes(x=RelSpeed))+geom_histogram()+labs(title =paste(p, ": Velo"),
#         x = "Velocity (mph)", y = "Frequency",
#         caption = "Trackman Data")
```

```{r tilt}
for (j in pitches) {
  pitch <- filter(player, TaggedPitchType == j)
  print(ggplot(pitch, aes(x=Tilt))+geom_histogram()+labs(title =paste(p, j, "Tilt"),
        x = "Tilt", y = "Frequency",
        caption = "Trackman Data"))+xlim(0,12)
}
# ggplot(player, aes(x=Tilt))+geom_histogram()+labs(title =paste(p, ": Tilt"),
#         x = "Tilt", y = "Frequency",
#         caption = "Trackman Data")
# ggplot(player, aes(x=SpinRate))+geom_histogram()+labs(title =paste(p, ": Spin"),
#         x = "Spin Rate (rpm)", y = "Frequency",
#         caption = "Trackman Data")
```


